version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: StreamEd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "8888:8888"  # Mapping the internal PostgreSQL port 8888 to external port 8888
    command: ["postgres", "-p", "8888"]  # Run PostgreSQL on port 8888

  ktor:
    image: my-ktor-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=admin
      - DB_POSTGRES_URL=jdbc:postgresql://postgres:8888/StreamEd  # Connect to PostgreSQL on port 8888
      - DB_POSTGRES_USER=postgres
      - HASH_SECRET_KEY=super-secret
      - JWT_SECRET=app-app-secret
      - PORT=8080
    depends_on:
      - postgres  # Ensure PostgreSQL starts before the Ktor app

  nginx:
    image: tiangolo/nginx-rtmp:latest
    ports:
      - "1935:1935"
    depends_on:
      - ktor
